name: Generate Archive and Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pack the repository
        run: |
          .github/tools/asset_packer.exe . -c .github/tools/packing.config AdvancedHatter.pak

      - name: Get version
        id: extract_version
        run: echo "::set-output name=version::$(jq -r '.version' _metadata)"

      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.txt
          files: AdvancedHatter.pak       
          tag_name: v${{ steps.extract_version.outputs.version }}
          name: Release V${{ steps.extract_version.outputs.version }}

      - name: Get changelog content
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "CHANGELOG.txt"